// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ODW_MultiLanguageSystem","status":true,"description":"[v1.1.0] - Manage game texts in several languages.","parameters":{"option":"Languages","folder":"languages","fonts":"[]","languages":"[\"{\\\"code\\\":\\\"cn\\\",\\\"label\\\":\\\"Chinese\\\",\\\"folder\\\":\\\"cn\\\",\\\"fontName\\\":\\\"\\\",\\\"fontSize\\\":\\\"0\\\",\\\"files\\\":\\\"[\\\\\\\"main\\\\\\\"]\\\",\\\"coreTexts\\\":\\\"\\\",\\\"miss\\\":\\\"Miss\\\",\\\"on\\\":\\\"ON\\\",\\\"off\\\":\\\"OFF\\\"}\",\"{\\\"code\\\":\\\"en\\\",\\\"label\\\":\\\"English\\\",\\\"folder\\\":\\\"eng\\\",\\\"fontName\\\":\\\"\\\",\\\"fontSize\\\":\\\"0\\\",\\\"files\\\":\\\"[\\\\\\\"main\\\\\\\"]\\\",\\\"coreTexts\\\":\\\"\\\",\\\"miss\\\":\\\"Miss\\\",\\\"on\\\":\\\"ON\\\",\\\"off\\\":\\\"OFF\\\"}\"]","useErrorLog":"false"}},
{"name":"ODW_MultiLanguageSystem_GalvMZ","status":false,"description":"[v2.0.0] - Patch for Galv MZ plugins.","parameters":{}}
];
